### ISSUE TITLE
中文目录不支持

### ISSUE THREAD

**Issue by maobaolong** [nl101531/MarkdownViewTools#1]
我的设置
md.path1 = D:/seafile/seafile_rpi//Seafile//note//工具使用

启动后，可以打开页面，列出文件，但是，在点击“工具使用文件夹下的文件时”，就报错了，看log中文显示乱码了

**Comment by mrdear** [comment]
有这个问题,linux下读取中文目录,上传之类的会出问题,暂时不知道怎么解决,你这个win下应该没啥问题,我就是win下开发的

**Comment by mrdear** [comment]
今天更新了一个版本,我win10下没问题,日志现在打的也很齐全,如果你那边还有问题,可以参考下日志看看
